Repository 0xPARC/pod2, pull requests merged in 2025-02, with the labels that each got.

#74 Prototype custom predicates
  .github/workflows/rustfmt.yml
  .github/workflows/typos.toml
  src/backends/mock_main/mod.rs
  src/backends/mock_main/operation.rs
  src/backends/mock_main/statement.rs
  src/backends/mock_signed.rs
  src/frontend/mod.rs
  src/frontend/operation.rs
  src/frontend/statement.rs
  src/middleware/custom.rs
  src/middleware/mod.rs
  src/middleware/operation.rs
  src/middleware/statement.rs
Labels: discussion, deductions

#49 Aard custom
  .gitignore
  book/src/SUMMARY.md
  book/src/custom.md
  book/src/custom1.md
  book/src/custom1b.md
  book/src/custom2.md
  book/src/customexample.md
  book/src/examples.md
  book/src/front_and_back.md
  book/src/simpleexample.md
Labels: deductions

#83 Frontend: simplify custom predicates interfaces
  src/backends/mock_main/mod.rs
  src/frontend/custom.rs
  src/frontend/mod.rs
  src/middleware/custom.rs
  src/middleware/mod.rs
Labels: frontend

#90 Serialize and hash custom predicates
  .github/workflows/typos.toml
  src/backends/mock_main/mod.rs
  src/backends/mock_main/statement.rs
  src/frontend/custom.rs
  src/frontend/mod.rs
  src/middleware/custom.rs
  src/middleware/mod.rs
  src/middleware/statement.rs
Labels: impl

#94 Featurize middleware types that are actually defined by the backend
  Cargo.toml
  README.md
  src/backends/mod.rs
  src/backends/plonky2.rs
  src/backends/plonky2/basetypes.rs
  src/backends/plonky2/mock_main/mod.rs
  src/backends/plonky2/mock_main/operation.rs
  src/backends/plonky2/mock_main/statement.rs
  src/backends/plonky2/mock_signed.rs
  src/backends/plonky2/mod.rs
  src/examples.rs
  src/frontend/custom.rs
  src/frontend/mod.rs
  src/middleware/basetypes.rs
  src/middleware/containers.rs
  src/middleware/custom.rs
  src/middleware/mod.rs
  src/middleware/statement.rs
Labels: impl
